#!/usr/bin/env python3
"""Run and analyze a Cortex-M AND-effect-suppression campaign.

This wrapper uses the two scripts generated by the instruction-skip-HPC project:

  * run_clock_glitch_hpc.py       -- discovers AND target-skip seed points
  * run_clock_glitch_hpc_long.py  -- performs a long exact-point/neighborhood run

The final report intentionally prints only the two distributions requested:

  1. no_fault_execution: no clock glitch, correct AND execution
  2. valid_skip_and_execution: valid metadata/response and result equal to the
     predefined AND target-skip result

The second group is an architectural-effect-suppression candidate. Without ETM
instruction trace it is not proof that the AND instruction was never fetched or
executed internally.

For the generated AND target, r0 enters the call holding 0x5A and r1 holds 0x3C.
`ands r0, r1` only overwrites r0 if it actually executes. Therefore:
  * normal AND result:      0x18
  * AND-suppression result: 0x5A

AND is a register-to-register write with no memory access, so LSUCNT is expected to
read zero in both the baseline and the skip rows. A nonzero LSUCNT would indicate the
trigger window is capturing more than the target function.

What this target adds: AND is a single-cycle flag-setting ALU op, the same class as
ADD/SUB/XOR, so it is a replication rather than a new mechanism test. Its value is in
controlling a known confound -- ADD/SUB/XOR were scanned with the old defaults
(ext_offset 0..40, 5 trials/point) while MOV and MUL used the current ones (ext pinned
to 0, 20 trials/point). MOV and MUL showed a 38/39 bimodality that the older ALU runs
did not. Running AND under the current defaults separates the two explanations:

  * bimodal 38/39  -> the split is a sampling artifact of the newer scan settings
  * single-valued 38 -> the bimodality is a real property of MOV and MUL

Expected baseline is 37 cycles, matching the other single-cycle ALU targets.
"""

from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Iterable

VERSION = "1.0.0"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    p.add_argument(
        "--project-dir",
        type=Path,
        default=Path.cwd(),
        help="directory containing run_clock_glitch_hpc.py and run_clock_glitch_hpc_long.py",
    )
    p.add_argument("--program", action="store_true", help="program firmware before the first hardware phase")
    p.add_argument("--firmware", type=Path, default=None)
    p.add_argument("--platform", default="CWLITEARM")

    p.add_argument("--seed-csv", type=Path, default=Path("and_seed_scan.csv"))
    p.add_argument("--output-csv", type=Path, default=Path("and_hpc_long_15h.csv"))
    p.add_argument(
        "--skip-search",
        action="store_true",
        help="require an existing seed CSV and go directly to the long run",
    )
    p.add_argument(
        "--analyze-only",
        type=Path,
        default=None,
        metavar="CSV",
        help="do not connect to hardware; print the two requested distributions from CSV",
    )

    # Discovery scan. ext_offset is pinned to 0 because no campaign on this board has
    # ever produced a hit at ext_offset > 0, and 20 trials per point (rather than 5)
    # gives a ~3%-rate point a reasonable chance of showing up.
    p.add_argument("--search-baseline", type=int, default=1000)
    p.add_argument("--search-success-target", type=int, default=20)
    p.add_argument("--search-trials-per-point", type=int, default=20)
    p.add_argument("--search-max-attempts", type=int, default=0)
    p.add_argument("--offset-start", type=float, default=-45.0)
    p.add_argument("--offset-stop", type=float, default=-30.0)
    p.add_argument("--offset-step", type=float, default=0.5)
    p.add_argument("--width-start", type=float, default=0.10)
    p.add_argument("--width-stop", type=float, default=0.60)
    p.add_argument("--width-step", type=float, default=0.025)
    p.add_argument("--ext-start", type=int, default=0)
    p.add_argument("--ext-stop", type=int, default=0)
    p.add_argument("--ext-step", type=int, default=1)
    p.add_argument("--repeat", type=int, default=1)
    p.add_argument("--seed", type=int, default=20260806)

    # Long run.
    p.add_argument("--duration-hours", type=float, default=15.0)
    p.add_argument("--baseline", type=int, default=1000)
    p.add_argument("--baseline-refresh-minutes", type=float, default=60.0)
    p.add_argument("--baseline-refresh-samples", type=int, default=100)
    p.add_argument("--exact-probability", type=float, default=0.70)
    p.add_argument("--neighbor-probability", type=float, default=0.30)
    p.add_argument("--seed-top-k", type=int, default=8)
    p.add_argument("--report-minutes", type=float, default=15.0)
    p.add_argument("--flush-seconds", type=float, default=15.0)
    p.add_argument("--append", action="store_true")

    return p.parse_args()


def resolve_under(project_dir: Path, path: Path) -> Path:
    return path if path.is_absolute() else project_dir / path


def require_file(path: Path, description: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{description} not found: {path}")


def run_command(command: list[str], cwd: Path) -> None:
    print("\n[command]", " ".join(str(item) for item in command), flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def count_seed_hits(path: Path) -> int:
    if not path.is_file():
        return 0
    count = 0
    with path.open(newline="") as fp:
        for row in csv.DictReader(fp):
            if (
                row.get("instruction") == "and"
                and row.get("classification") == "target_skip_candidate"
            ):
                count += 1
    return count


def parse_int(value: str | None) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(value, 0)
    except ValueError:
        try:
            return int(float(value))
        except ValueError:
            return None


def cycle_distribution(rows: Iterable[dict[str, str]]) -> Counter[int]:
    distribution: Counter[int] = Counter()
    for row in rows:
        cycle = parse_int(row.get("cycles"))
        if cycle is not None:
            distribution[cycle] += 1
    return distribution


def format_distribution(distribution: Counter[int]) -> str:
    if not distribution:
        return "[]"
    return "[" + ", ".join(
        f"({cycle}, {count})" for cycle, count in sorted(distribution.items())
    ) + "]"


def analyze_csv(path: Path) -> None:
    require_file(path, "campaign CSV")
    with path.open(newline="") as fp:
        rows = list(csv.DictReader(fp))

    no_fault_rows = [
        row
        for row in rows
        if row.get("instruction") == "and"
        and row.get("classification") == "normal"
        and (
            row.get("parameter_source") == "no_fault"
            or row.get("phase") in {"baseline", "baseline_initial", "baseline_refresh"}
        )
    ]

    valid_skip_rows = [
        row
        for row in rows
        if row.get("instruction") == "and"
        and row.get("classification") == "target_skip_candidate"
        and row.get("phase") not in {"baseline", "baseline_initial", "baseline_refresh"}
    ]

    no_fault_dist = cycle_distribution(no_fault_rows)
    skip_dist = cycle_distribution(valid_skip_rows)

    print("\n[requested AND comparison]")
    print(f"no_fault_execution: n={sum(no_fault_dist.values())}")
    print(f"  cycle_count_distribution={format_distribution(no_fault_dist)}")
    if no_fault_dist:
        total = sum(no_fault_dist.values())
        for cycle, count in sorted(no_fault_dist.items()):
            print(f"  cycles={cycle}: {count}/{total} ({100.0 * count / total:.6f}%)")

    print(f"valid_skip_and_execution: n={sum(skip_dist.values())}")
    print(f"  cycle_count_distribution={format_distribution(skip_dist)}")
    if skip_dist:
        total = sum(skip_dist.values())
        for cycle, count in sorted(skip_dist.items()):
            print(f"  cycles={cycle}: {count}/{total} ({100.0 * count / total:.6f}%)")
    else:
        print("  No valid AND target-skip candidates were present in this CSV.")

    print("\n[operational definitions]")
    print("  no_fault_execution = no clock glitch + valid metadata + normal AND result")
    print("  valid_skip_and_execution = clock glitch + valid metadata/response + result equals AND skip reference")


def main() -> int:
    args = parse_args()
    project_dir = args.project_dir.expanduser().resolve()

    if args.analyze_only is not None:
        analyze_csv(resolve_under(project_dir, args.analyze_only).resolve())
        return 0

    short_runner = project_dir / "run_clock_glitch_hpc.py"
    long_runner = project_dir / "run_clock_glitch_hpc_long.py"
    require_file(short_runner, "short scan runner")
    require_file(long_runner, "long-run runner")

    seed_csv = resolve_under(project_dir, args.seed_csv).resolve()
    output_csv = resolve_under(project_dir, args.output_csv).resolve()
    firmware = None if args.firmware is None else resolve_under(project_dir, args.firmware).resolve()

    if output_csv == seed_csv:
        raise ValueError("--seed-csv and --output-csv must be different")

    need_search = count_seed_hits(seed_csv) == 0
    if args.skip_search and need_search:
        raise RuntimeError(
            f"--skip-search was requested, but {seed_csv} contains no AND target-skip candidates"
        )

    programmed = False
    if need_search:
        search_command = [
            sys.executable,
            str(short_runner),
            "--instruction", "and",
            "--platform", args.platform,
            "--baseline", str(args.search_baseline),
            "--success-target", str(args.search_success_target),
            "--trials-per-point", str(args.search_trials_per_point),
            "--max-attempts", str(args.search_max_attempts),
            "--offset-start", str(args.offset_start),
            "--offset-stop", str(args.offset_stop),
            "--offset-step", str(args.offset_step),
            "--width-start", str(args.width_start),
            "--width-stop", str(args.width_stop),
            "--width-step", str(args.width_step),
            "--ext-start", str(args.ext_start),
            "--ext-stop", str(args.ext_stop),
            "--ext-step", str(args.ext_step),
            "--repeat", str(args.repeat),
            "--randomize",
            "--seed", str(args.seed),
            "--csv", str(seed_csv),
        ]
        if args.program:
            search_command.append("--program")
            programmed = True
        if firmware is not None:
            search_command.extend(["--firmware", str(firmware)])
        run_command(search_command, project_dir)

        hits = count_seed_hits(seed_csv)
        if hits == 0:
            print(
                "\nNo valid AND target-skip seed was found. The long-run phase was not started.\n"
                "Expand the search range or increase --search-trials-per-point, then rerun.",
                file=sys.stderr,
            )
            return 2
        print(f"\n[seed discovery] valid AND candidates={hits} CSV={seed_csv}")
    else:
        print(f"[seed discovery] reusing {count_seed_hits(seed_csv)} AND candidates from {seed_csv}")

    long_command = [
        sys.executable,
        str(long_runner),
        "--instruction", "and",
        "--seed-csv", str(seed_csv),
        "--output-csv", str(output_csv),
        "--platform", args.platform,
        "--duration-hours", str(args.duration_hours),
        "--baseline", str(args.baseline),
        "--baseline-refresh-minutes", str(args.baseline_refresh_minutes),
        "--baseline-refresh-samples", str(args.baseline_refresh_samples),
        "--exact-probability", str(args.exact_probability),
        "--neighbor-probability", str(args.neighbor_probability),
        "--seed-top-k", str(args.seed_top_k),
        "--report-minutes", str(args.report_minutes),
        "--flush-seconds", str(args.flush_seconds),
    ]
    if args.append:
        long_command.append("--append")
    if args.program and not programmed:
        long_command.append("--program")
    if firmware is not None:
        long_command.extend(["--firmware", str(firmware)])

    run_command(long_command, project_dir)
    analyze_csv(output_csv)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as exc:
        print(f"\nCampaign command failed with exit code {exc.returncode}", file=sys.stderr)
        raise SystemExit(exc.returncode)
    except Exception as exc:
        print(f"\nerror: {exc}", file=sys.stderr)
        raise SystemExit(1)
